version: '3.7'

services:
  node:
    image: cenk1cenk2/node-fnm:latest
    environment:
      DEFAULTS_LOGS: 'true'
      PROXY_WORKSPACE_ONLY: 'true'
    ports:
      - 9229:9229
    volumes:
      - .:/data
